version: "3.9"
services:
  mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    networks:
      - compose-bridge
  
  alurabooks:
    image: aluradocker/alurabooks:1.0
    container_name: alurabooks
    networks:
      - compose-bridge
    volumes:
      - ./data:/data/db
    ports:
      - 3000:3000
networks:
  compose-bridge:
    driver: bridge